build(docker.sh): Remove flag `--progress=plain` from docker build
Summary:
Necessary to remove it for Windows OS, because Windows runner on Github actions
do not support BuildX and it also doesn't allow to install it due to error:
```
ERROR: Error response from daemon: Windows does not support privileged mode
```

Test plan:
* Pipeline passes