ci(scripts): Fix docker squash step on github workflow
Summary:
This commit fixes the docker squash step on github workflow.
It fixes the error:
```
ERROR    module 'docker' has no attribute 'version_info'
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/docker_squash/image.py", line 357, in _save_image
    if docker.version_info[0] < 3:
AttributeError: module 'docker' has no attribute 'version_info'
WARNING  An error occured while saving the sha256:8f1c60b969cc52268d9418fdcbe7ff2ee5c248fa8a767cef1b9dade805d3f622 image, retrying...
ERROR    Couldn't save sha256:8f1c60b969cc52268d9418fdcbe7ff2ee5c248fa8a767cef1b9dade805d3f622 image!
ERROR    Execution failed, consult logs above.
Error: Process completed with exit code 1.
```
The fix is to force the installation of docker with version `5.0.3`
instead of installing the latest version since docker version 6.0.0
produces the error `module 'docker' has no attribute 'version_info'`.

Test plan:
* Trigger pipeline