build(RegularGrid): Unshare the field grid_ between OpenMP threads
Summary:
This is necessary because the compilers MSVC and MinGW do not support sharing
object fields to OpenMP threads:
```
RegularGrid.hpp(204,50): error C3028: 'MobileRT::RegularGrid<MobileRT::Triangle>::grid_': only a variable or static data member can be used in a data-sharing clause
```

Test plan:
* Pipeline passes