fix(CMakeLists.txt): Add gcc flag `-fprofile-update=atomic`
Summary:
This flag is necessary to avoid the following error when generating
the code coverage:
```
geninfo: ERROR: Unexpected negative count '-1' for /home/runner/work/MobileRT/MobileRT/app/MobileRT/Accelerators/BVH.hpp:357.
Perhaps you need to compile with '-fprofile-update=atomic
(use "geninfo --ignore-errors negative ..." to bypass this error)
Error: Process completed with exit code 1.
```

Test plan:
* Pipeline passes