third_party: Update `pcg-cpp` dependency to use `master` branch
Summary:
This commit updates the `pcg-cpp` dependency back to use the `master`
branch since otherwise the Windows 2019 MinGW pipeline would fail
compiling the project with the following error:
```
MobileRT\app\third_party\pcg-cpp\include\pcg_uint128.hpp(74,1):
fatal error C1189: #error:  Unable to determine target endianness
[D:\a\MobileRT\MobileRT\build_release\MobileRT\MobileRT.vcxproj]
```

Test plan:
* Run the pipeline