ci(android.yml): Increase timeout to 3min for "Download Gradle packages artifact" step
Summary:
The goal is to check if this step in AndroidTests job starts to fail less times
with the error:
```
Starting download of artifact to: /home/runner/.gradle
(node:1802) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: The action 'Download Gradle packages artifact' has timed out after 2 minutes.
```

Test plan:
* Pipeline passes